#+title: 研究でのプログラム整理
#+SETUPFILE: ../../2016/04/setup/customized-theme.setup

研究活動におけるディレクトリ構造の管理について記している。

* 理想・望ましいこと
- 記憶に頼らずに、何について、どのように取り組んでいるのかを、理解しやすい
- 過去の実験は、どのような設定で実行されたのか、たどることができる
- 再実験が容易である
- 一度実装したコードは再利用される(同じコードを何度も書き直す必要がない)

* ディレクトリ構成案
次のようなディレクトリ構成

#+begin_example
.
├── [実験を区別するための名称]
│   ├── readme.txt(実験内容について記述。結果や考察も埋め込んでもいいと思っている)
│   ├── agenda.org(今後やるべきことややりたいこと、やってきたこと、実験に取り組んだ記録を記述)
│   ├── doc(実験に関する詳細な記述。readmeで十分として作らないことも多い。)
│   │   ├── text1.tex
│   │   ├── text2.pdf
│   ├── config.json(実験の設定)
│   ├── log.txt(最後に行った実験での標準入出力を記録)
│   ├── run.sh(これの実行によって、実験を行う)
│   ├── preview.sh(実験結果をいい感じに見ていく)
│   ├── data(実験に用いる元データ)
│   │   ├── data1.dat
│   │   ├── data2.csv
│   ├── work(実験で生成したデータや結果を出力する)
│   │   ├── result1.dat
│   │   ├── result2.dat
│   │   ├── result3.png
│   │   ├── hoge(必要ならconfig.jsonを書き換えるごとに結果の出力先を分割する。)
│   │   │   ├── result.png
│   │   │   ├── copied_config.json(この実験を行った際の設定情報をコピーしておく)
│   ├── src
│   │   ├── program1.py(実験に使用するプログラム。多くて7個程度に留める)
│   │   ├── program2.cpp
│   │   ├── program3.hpp
│   ├── test(プログラム検証用のテスト。堅くなくてよいし、作らないことも多い)
│   │   ├── test1.py
#+end_example

** 重要なファイル説明
- readme.txt :: 実験の目的は何か
- agenda.org :: 何をする予定か、何をしてきたのか
- run.sh :: 実験を行う
- preview.sh :: 実験結果を確認する

** 注意事項

実験プログラムはできるだけ外のディレクトリのファイルを参照しないように注意する。
これは再実験を確実にするためである。別のディレクトリのコードを編集・削除・移動してしまって、後方互換性を失い、再実験ができなくなることは避ける。もちろん十分に注意すれば不可能ではないが、コストに見合わないというのが今の結論。

実験の計画が膨らんでいき、ディレクトリが増えていった場合は、実験をグループに分割すること。
この時にプログラムがディレクトリ内で完結していれば、互換性の維持は容易である。

* TODO 要検討

** makefileの活用
run.sh や preview.sh は makefileでまとめてしまったほうが便利かもしれない。

メリット
- 一つのファイルにスッキリまとまり、編集の手間が省ける。
- 依存関係を扱えるためconfig.jsonに依存させて前処理を行うかどうかなどを自動化できる

デメリット(懸念)
- cppなどのコンパイル目的でmakeを使う場合に、ファイルの依存関係とmakefileが共存することになり煩雑になるのでは
** ファイルの重複について
現在の記述では、ファイルをコピーして使いまわすことになる。一つのファイルを改善しても、他のファイルには反映されない。使いまわされるファイルのバージョンが管理されないことになる。

使い回し続けるような核になるプログラムについては、別にひとつディレクトリを作成し、常にそこからコピーしていくようにするのはありだ。


* 参考文献
- [[http://www.chokkan.org/publication/coding-for-researchers.pdf][研究者流コーディングの極意]]
# ([[file:~/howm/2017/07/coding-for-researchers.pdf][ローカル:研究者流コーディングの極意]])
- [[http://yukitask.textfile.org/][YukiTask]]
